sudo: false
language: node_js
matrix:
  include:
  - node_js: 5.9 # Latest stable
    env: REPORT_COVERAGE=true
  - node_js: 4.4 # LTS
    env: NPM_DEPLOY=true
  - node_js: 0.10 # Minimum supported
script:
- npm test
- npm run doc # Ensures ESDoc generation doesn't fail
after_success:
- '[[ "$REPORT_COVERAGE" = true ]] && cat coverage/lcov.info | ./node_modules/.bin/codecov'
- '[[ "$REPORT_COVERAGE" = true ]] && cat coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter'
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: amercier/esviz # Prevents publishing on PRs
    condition: $NPM_DEPLOY = true # Prevents publishing on each matrix build
cache:
  directories:
  - $HOME/.npm
